"""create table

Revision ID: 42086b55c729
Revises: 2179c69b81f1
Create Date: 2024-09-24 16:25:05.493052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42086b55c729'
down_revision: Union[str, None] = '2179c69b81f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oauth_account', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'oauth_account', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'oauth_account', type_='foreignkey')
    op.drop_column('oauth_account', 'user_id')
    # ### end Alembic commands ###
